INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (1, 'Elder', 2000);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (2, 'Hugo', 1988);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (3, 'Isildro', 1997);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (4, 'Otávio', 1982);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (5, 'Elias', 1953);
INSERT INTO PESSOA (ID, NOME, ANONASCIMENTO) VALUES (6, 'Rodrigo', 1985);

ALTER SEQUENCE pessoa_seq RESTART WITH 7;